### PR TITLE
Allow Usage in Family Document

### PR DESCRIPTION
**Pull request by sixtysecondrevit**
Added an If/Else statement to allow this node to work in a project
document or in a family document. This was by request of a user on the
Dynamo forums.
http://dynamobim.org/forums/topic/using-dynamo-in-family-templates/#post-39076

### CODE REVIEW

**Comment by andydandy74** [comment]
Nice catch @sixtysecondrevit  - I'll merge this in and add it to the next release.

**Comment by dimven** [comment]
You could try to further streamline it like so:
>if doc.IsFamilyDocument : doc_create = doc.FamilyCreate
>else : doc_create = doc.Create
>for curve in curves:
>>detcurve = doc_create.NewDetailCurve(view, curve.ToRevitType())
>>elementlist.append(detcurve)

**Comment by andydandy74** [comment]
Will do, @dimven - thanks!

**Comment by sixtysecondrevit** [comment]
You both are truly the python masters. I gotta say, I'm learning a lot from
the both of you! Thank you!

On Thursday, February 18, 2016, Andreas Dieckmann <notifications@github.com>
wrote:

> Will do, @dimven <https://github.com/dimven> - thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CAAD-RWTH/ClockworkForDynamo/pull/90#issuecomment-185643186>
> .
>


-- 
-john p
<http://sixtysecondrevit.blogspot.com/>
<https://github.com/sixtysecondrevit/RhythmForDynamo>

**Pull request merged**
